---
title: "Posibles resultados"
---

```{r, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
source("code/rvest_clasificacion.r")
```

::: {}
### Campe贸n `r emoji::flag("Argentina")` Finalista `r emoji::flag("France")`

```{r echo=FALSE}
sims_lista_puntos[[1]] %>% slice(1:3)  %>% select(Puntos = PuntosTot)%>% kbl() %>% kable_paper(full_width = T)
```



::: 

::: {style="color: #ccc;"}

### Campe贸n `r emoji::flag("France")` Finalista `r emoji::flag("Argentina")`

```{r echo=FALSE}
sims_lista_puntos[[5]] %>% slice(1:3) %>% select(Puntos = PuntosTot)%>% kbl() %>% kable_paper(full_width = T) %>% row_spec(0:3, color = "darkgrey")
```


### Campe贸n `r emoji::flag("Argentina")` Finalista `r emoji::flag("Morocco")`

```{r echo=FALSE}
sims_lista_puntos[[3]] %>% slice(1:3) %>% select(Puntos = PuntosTot) %>% kbl() %>% kable_paper(full_width = T) %>% row_spec(0:3, color = "darkgrey")
```



### Campe贸n `r emoji::flag("Morocco")` Finalista `r emoji::flag("Argentina")`
```{r echo=FALSE}
sims_lista_puntos[[6]] %>% slice(1:3) %>% select(Puntos = PuntosTot)%>% kbl() %>% kable_paper(full_width = T)%>% row_spec(0:3, color = "darkgrey")
```

::: 
