---
title: "Porra"
---


```{r opciones, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```


## Octavos
```{r}
porra_list[["octavos"]] %>% 
    mutate(across(everything(),
                  ~ cell_spec(.x,"html",
                                background = ifelse(.x %in% equipos_octavos, "green", ""),
                                color = ifelse(.x %in% equipos_octavos, "white", "")))) %>% 
    kbl(format = "html", escape = F) %>% 
    kable_paper(full_width = F)
```

## Cuartos
```{r}
porra_list[["cuartos"]] %>% 
    mutate(across(everything(),
                  ~ cell_spec(.x,"html",
                                background = ifelse(.x %in% equipos_cuartos, "green", ""),
                                color = ifelse(.x %in% equipos_cuartos, "white", "")))) %>% 
    kbl(format = "html", escape = F) %>% 
    kable_paper(full_width = F)
```

## Semifinales
```{r}
porra_list[["semis"]] %>% 
    mutate(across(everything(),
                  ~ cell_spec(.x,"html",
                                background = ifelse(.x %in% equipos_semis, "green", ""),
                                color = ifelse(.x %in% equipos_semis, "white", "")))) %>% 
    kbl(format = "html", escape = F) %>% 
    kable_paper(full_width = F)
```

## Final
```{r}
porra_list[["final"]] %>% 
    mutate(across(everything(),
                  ~ cell_spec(.x,"html",
                                background = ifelse(.x %in% equipos_final, "green", ""),
                                color = ifelse(.x %in% equipos_final, "white", "")))) %>% 
    kbl(format = "html", escape = F) %>% 
    kable_paper(full_width = F)
```

## CAMPEÓN
```{r}
porra_list[["campeon"]] %>% 
    mutate(across(everything(),
                  ~ cell_spec(.x,"html",
                                background = ifelse(.x %in% campeon, "green", ""),
                                color = ifelse(.x %in% campeon, "white", "")))) %>% 
    kbl(format = "html", escape = F) %>% 
    kable_paper(full_width = F)
```


