on:
  schedule:
    - cron: '30 17,21 * * *'

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("rvest")
          install.packages("dplyr")
          install.packages("purrr")
          install.packages("kableExtra")
          install.packages("emoji")
          install.packages("stringr")
          install.packages("readxl")
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
